STEP3: 出品APIを作る
hinako1217/mercari-build-training pull request #2
Opened 2024-02-18 15:16 UTC by hinako1217

## What

### **新しい商品を登録する** 
nameとcategoryをスライスに追加し、JSONファイルに書き込む
 

### **商品一覧を取得する** 
JSONファイルからitemsを読み込む
 

### **画像を登録する**
画像のファイルパスをハッシュ化した後、name・categoryと共にスライスに追加し、JSONファイルに書き込む
 

### **商品の詳細を返す**
JSONファイルから、urlのidに対応する商品の詳細を返す
 
## Comment
改善点などありましたらコメントいただけると嬉しいです
## CHECKS :warning:

Please make sure you are aware of the following.

- [ ] **The changes in this PR doesn't have private information

2024-02-19 01:34 UTC, kswbr-tomoka approved these changes

2024-02-19 12:04 UTC, NamikoToriyama requested changes
次のstepではfirst-pull-requestではなくstep4用のブランチを切るようにしてください🙏

2024-02-19 12:04 UTC, NamikoToriyama commented on go/app/main.go
> +	imagepath := c.FormValue("image")
[Q] リクエストで送った画像は保存されていますか？

2024-02-19 12:04 UTC, NamikoToriyama commented on go/app/main.go
> +	id, _ := strconv.Atoi(c.Param("id")) //string to int
_にはerrorが帰ってくるので、エラー処理をしてください🙏

2024-02-19 12:04 UTC, NamikoToriyama commented on go/app/main.go
> +	}
２回目以降にitemを追加できるか確認してもらってもいいでしょうか？

以下のようになりますか？

```
1回目
$ curl -X POST \
  --url 'http://localhost:9000/items' \
  -d 'name=jacket' \
  -d 'category=fashion'

expected items.json
{"items": [{"name": "jacket", "category": "fashion"}]}

2回目
$ curl -X POST \
  --url 'http://localhost:9000/items' \
  -d 'name=ring' \
  -d 'category=accessory'

expected items.json
{"items": [{"name": "jacket", "category": "fashion"}, {"name": "ring", "category": "accessory"}]}
```

2024-02-19 12:04 UTC, NamikoToriyama commented on go/app/main.go
> +	}
もしうまくいってない場合は、書き込む前に既存のjsonを読み込むようにコードを修正してください🙏

2024-02-20 02:14 UTC, hinako1217 commented
プログラムを変更したところ、
curl -X POST \                                           
  --url 'http://localhost:9000/items' \
  -d 'name=jacket' \
  -d 'category=fashion'
{"message":"Internal Server Error"}
このようなエラーが出るようになってしまいました。

サーバーのログ↓
{"time":"2024-02-20T11:10:53.421432+09:00","level":"FATAL","prefix":"-","file":"main.go","line":"125","message":"EOF"}
exit status 1

2024-02-20 07:17 UTC, SuzuToyoda commented
@hinako1217 torichanからのコメントで修正したCommitがあればそれをコメントとして追記するようにしてくれるとわかりやすいと思います！
↓のようにコピペできるのでコメントしてみてください
[d7ff52b](https://github.com/hinako1217/mercari-build-training/pull/2/commits/d7ff52bda6798d20bb93e97e5e7542329b74ad20)

2024-02-20 08:36 UTC, hinako1217 commented on go/app/main.go
> +	imagepath := c.FormValue("image")
保存されています
<img width="283" alt="スクリーンショット 2024-02-20 17 36 18" src="https://github.com/hinako1217/mercari-build-training/assets/133786698/9a9ba2dd-060b-41e3-a5b5-e31c33cb4fd0">

2024-02-20 08:39 UTC, hinako1217 commented on go/app/main.go
> +	id, _ := strconv.Atoi(c.Param("id")) //string to int
[481f89e](https://github.com/hinako1217/mercari-build-training/pull/2/commits/481f89eec601ef6ba3de6df29cf8db72ec24f603)
修正しました

2024-02-20 08:42 UTC, hinako1217 commented on go/app/main.go
> +	}
```
{"items":[{"name":"jacket","category":"fashion","image_name":"8aff12fae61ae6ba62974b102d6cbc01f3bb1d25c546d1262cd8a76fd73bceae.jpg"},{"name":"skirt","category":"fashion","image_name":"74be3d0b49aa4b89423f8117b22bf922ddd4e43fdbd1a9060012727c761781b1.jpg"}]}
```
2回目以降も追加できています

2024-02-20 10:09 UTC, NamikoToriyama approved these changes
全部細かい部分の修正なので、次にもし進みたければ進んでも大丈夫です🙆‍♀️
直していただければ再度確認します

2024-02-20 10:09 UTC, NamikoToriyama commented on go/app/main.go
> +	return itemlist
[nits] 返り値にerrorを足して、他の関数でerrorハンドリングをできるようにしましょう

```suggestion
func decodeJson() (ItemList, error) {
	jsonfile, err := os.Open("items.json")
	if err != nil {
		nil, err
	}
	defer jsonfile.Close()

	//decode
	var itemlist ItemList
	decoder := json.NewDecoder(jsonfile)
	if err := decoder.Decode(&itemlist); err != nil {
		return nil, error
	}

	return itemlist,nil
```

2024-02-20 10:09 UTC, NamikoToriyama commented on go/app/main.go
> +var itemlist ItemList
[nits] できれば、ここでitemListを宣言しないで、addItem内で変数を宣言するようにしたいです。

2024-02-20 10:09 UTC, NamikoToriyama commented on go/app/main.go
> +		log.Fatal(err)
[nits] log.Fatal を使わないで、できればerrorをreturnしてあげるようにしましょう。他のエラー処理も同様です。
エラーコードはその場所によって適切なコードを利用できると良いです。

```suggestion
     return c.JSON(http.StatusInternalServerError, Response{Message: err.Error()})

```

2024-02-22 01:15 UTC, merged

2024-02-26 04:37 UTC, hinako1217 commented on go/app/main.go
> +	return itemlist
[439c998](https://github.com/hinako1217/mercari-build-training/pull/6/commits/439c998e1bc1108a09b890b52bd66e5b49f979bf)
修正しました

2024-02-26 04:38 UTC, hinako1217 commented on go/app/main.go
> +		log.Fatal(err)
[439c998](https://github.com/hinako1217/mercari-build-training/pull/6/commits/439c998e1bc1108a09b890b52bd66e5b49f979bf)
修正しました

2024-02-26 04:38 UTC, hinako1217 commented on go/app/main.go
> +var itemlist ItemList
[e9478bd](https://github.com/hinako1217/mercari-build-training/pull/6/commits/e9478bdc72dcf5d82015ac2fd3a92ed5dfbaba63)
修正しました